#!/bin/bash
# Author - Akshay Gupta
# Version - 1.0.0
# Description - Installs and Configures LEMP Stack and then Wordpress for Port 80 only, in just 1 click.

installations() {
apt update -y; apt upgrade -y; apt dist-upgrade -y;
apt install -y software-properties-common;
add-apt-repository -y ppa:ondrej/php;
apt update -y;
apt install nginx -y;
apt install php7.1-mcrypt php7.1-intl php7.1-curl php7.1-xsl php7.1-mbstring php7.1-xsl php7.1-zip php7.1-soap php7.1-gd php7.1-bcmath php7.1-mysql php7.1-fpm -y;
apt install mysql-server mysql-client -y;
apt install composer -y;
}

conf_php() {
sed -i 's/memory_limit = -1/memory_limit = 2G/g' /etc/php/7.1/cli/php.ini
sed -i 's/max_execution_time = 30/max_execution_time = 1800/g' /etc/php/7.1/cli/php.ini
sed -i 's/zlib.output_compression = Off/zlib.output_compression = On/g' /etc/php/7.1/cli/php.ini

cat /etc/php/7.1/cli/php.ini | grep memory_limit
cat /etc/php/7.1/cli/php.ini | grep max_execution_time
cat /etc/php/7.1/cli/php.ini | grep 'zlib.output_compression ='

sed -i 's/memory_limit = 128M/memory_limit = 2G/g' /etc/php/7.1/fpm/php.ini
sed -i 's/max_execution_time = 30/max_execution_time = 1800/g' /etc/php/7.1/fpm/php.ini
sed -i 's/zlib.output_compression = Off/zlib.output_compression = On/g' /etc/php/7.1/fpm/php.ini

cat /etc/php/7.1/fpm/php.ini | grep memory_limit
cat /etc/php/7.1/fpm/php.ini | grep max_execution_time
cat /etc/php/7.1/fpm/php.ini | grep 'zlib.output_compression ='
service php7.1-fpm restart
}

conf_nginx() {
mkdir -p /etc/nginx/website;
if [[ ! -e /etc/nginx/php_loc.conf ]]; then
cat >> /etc/nginx/php_loc.conf << PHP_BLOCK
#	pass PHP scripts to FastCGI server
	location ~ \.php$ {
	root           /etc/nginx/website;
	fastcgi_index  index.php;
#	try_files \$uri =404;
#		With php-fpm (or other unix sockets):
	fastcgi_pass fastcgi_backend;
	include        fastcgi_params;
	fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
}
PHP_BLOCK
fi
if [[ ! -e /etc/nginx/sites-available/website ]]; then
	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/website;

cat >> /etc/nginx/sites-available/website.tmp << UPSTREAM
upstream fastcgi_backend {
	server  unix:/run/php/php7.1-fpm.sock;
}
UPSTREAM
	cat /etc/nginx/sites-available/website.tmp /etc/nginx/sites-available/website > /etc/nginx/sites-available/website.new;
	mv /etc/nginx/sites-available/website.new /etc/nginx/sites-available/website;
	rm -rf /etc/nginx/sites-available/website.tmp;
	sed -i 's/fastcgi_pass 127.0.0.1:9000/fastcgi_pass 127.0.0.1:9000;\
	include \/etc\/nginx\/php_loc.conf/g' /etc/nginx/sites-available/website;
	sed -i 's/root \/var\/www\/html/root \/etc\/nginx\/website/g' /etc/nginx/sites-available/website;
	sed -i 's/index index.html index.htm index.nginx-debian.html/index index.php index.html index.htm index.nginx-debian.html/g' /etc/nginx/sites-available/website;
	sed -i 's/\include \/etc\/nginx\/sites-enabled\/\*/include \/etc\/nginx\/sites-enabled\/website/g' /etc/nginx/nginx.conf;
fi
if [[ ! -e /etc/nginx/sites-enabled/website ]]; then
	ln -s /etc/nginx/sites-available/website /etc/nginx/sites-enabled/;
fi
if [[ ! -e /etc/nginx/website/test.php ]]; then
	echo '<?php phpinfo(); ?>' > /etc/nginx/website/test.php;
fi
service nginx restart
}
conf_db() {
	mysql -u root -e "
	create database websiteDB;
	CREATE USER admin@localhost IDENTIFIED BY 'password';
	GRANT ALL PRIVILEGES ON *.* TO admin@localhost;
	FLUSH PRIVILEGES;" -h localhost;
}
conf_wp() {
	cd /root/
if [[ ! -e latest.tar.gz ]]; then
	wget http://wordpress.org/latest.tar.gz -O latest.tar.gz
fi
if [[ ! -d wordpress ]]; then
	tar xzf latest.tar.gz
fi
	cd wordpress
	cd /root/
	cp wordpress/* /etc/nginx/website/ -r
	mkdir -p /etc/nginx/website/wp-content/uploads
	chown -R :www-data /etc/nginx/website/*
	rm -rf /etc/nginx/sites-enabled/website;
	ln -s /etc/nginx/sites-available/website /etc/nginx/sites-enabled/;
	service nginx restart;
}

echo "1. Updates, Upgrades and Distribution Upgrades (Reboot is required)"
echo "2. Configuring php.ini for nginx and Wordpress"
echo "3. Configuring nginx.conf and sites-available/website for php and Wordpress"
echo "4. Creating DB and User"
echo "5. Downloading and setting up latest Wordpress version"
echo "7. To perform all steps 01 to 05 quietly with all log in /root/wordpress_lemp_stack_setup.log (without any reboot)."
echo "Default Choice is 7."

if [ -z $1 ]; then
	read choice
fi

if [ -z $choice ]; then
	choice="$1"
fi

case $choice in
1)
installations
echo -e "All Installations are done.\nNow your system will reboot."
read -p "Press Enter to reboot" </dev/tty
reboot
;;
2)
conf_php
;;
3)
conf_nginx
;;
4)
conf_db
;;
5)
conf_wp
;;
7)
echo "=====================START=========================="				>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Updates, Upgrades and Distribution Upgrades"					>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Updates, Upgrades and Distribution Upgrades"
installations										>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Configuring php.ini for nginx and Wordpress"					>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Configuring php.ini for nginx and Wordpress"
conf_php										>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Configuring nginx.conf and sites-available/website for php and Wordpress"		>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Configuring nginx.conf and sites-available/website for php and Wordpress"
conf_nginx										>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Creating DB and User"								>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Creating DB and User"
conf_db											>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Downloading and setting up latest Wordpress version"				>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "Downloading and setting up latest Wordpress version"
conf_wp											>> /root/wordpress_lemp_stack_setup.log  2>&1
echo "======================END==========================="				>> /root/wordpress_lemp_stack_setup.log  2>&1
exit
;;
*)
loc="$(readlink -f ${BASH_SOURCE[0]})"
echo "Running $loc with Choice 07"
read -p "Press Enter to continue" </dev/tty
bash $loc 7
;;
esac

echo "Database Name: 	websiteDB"
echo "Username: 	admin"
echo "Password: 	password"
echo "Database Host: 	localhost"
